blueprints/alumnos_blueprint.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from config import Config
import pymysql
from models.alumno_models import get_all_alumnos, get_alumno_by_dni, get_alumno_by_id, add_alumno, delete_alumno, update_alumno


# Definición del blueprint

alumnos_bp = Blueprint('alumnos', __name__)


@alumnos_bp.route("/registrar", methods = ["GET", "POST"])
def registra():
    if request.method == "POST":
        dni = request.form['dni']
        nombre = request.form['nombre']
        apellido = request.form['apellido']
        fecha_nacimiento = request.form['fecha']
        email = request.form['email']
        telefono = request.form['telefono']
        

        try:
            add_alumno(dni, nombre, apellido, fecha_nacimiento, email, telefono)
            flash("El alumno se ha agregado correctamente", "success")
        except pymysql.MySQLError:
            flash("No se pudo registrar el alumno", "danger")
    return render_template("registrar_alumno.html")



@alumnos_bp.route("/consultar", methods = ["GET", "POST"])
def consulta():
    if request.method == "POST":
        dni = request.form['dni']
        alumno_buscado = get_alumno_by_dni(dni)

        if alumno_buscado:
            return render_template("consultar_alumno.html", alumno = alumno_buscado)
        
        else:
            flash("No se pudo encontrar ningun alumno con el DNI proporcionado", "danger")
            return redirect(url_for('consulta'))
    return render_template("consultar_alumno.html")



@alumnos_bp.route("/eliminar/<int:id>")
def eliminarAlumnos(id):
    
    try:
        delete_alumno(id)
        flash("alumno eliminado", "success")
    except pymysql.MySQLError:
        flash("No se pudo eliminar el alumno, tiene cursos registrados", "danger")
    return redirect(url_for('lista'))


# return render_template("eliminar_alumno.html")

@alumnos_bp.route("/listar")
def lista():
    listAlumnos = get_all_alumnos()
    return render_template("listar_alumno.html", total_alumnos = listAlumnos)



@alumnos_bp.route("/modificar", methods = ["GET", "POST"])
@alumnos_bp.route("/modificar/<int:alumnoid>", methods = ["GET", "POST"])
def modifica(alumnoid=None):
    if request.method == "POST":
        if "buscar" in request.form:
            dni = request.form['dni']
            alumno_buscado = get_alumno_by_dni(dni)

            if alumno_buscado:
                return render_template("modificar_alumno.html", alumno = alumno_buscado)
            
            else:
                flash("No se pudo encontrar ningun alumno con el DNI proporcionado", "danger")
                return redirect(url_for('modifica'))
            
        elif "modificar" in request.form:
            alumnoid = request.form['alumnoid']
            dni = request.form['dni']
            nombre = request.form['nombre']
            apellido = request.form['apellido']
            fecha_nacimiento = request.form['fecha']
            email = request.form['email']
            telefono = request.form['telefono']

            try:
                update_alumno(alumnoid, dni, nombre, apellido, fecha_nacimiento, email, telefono)
                flash("Los datos del alumno han sido actualizados", "success")
            except pymysql.MySQLError:
                flash("No se pudieron actualizar los datos del alumno", "danger")
            return render_template("modificar_alumno.html")   
         
        elif "eliminar" in request.form:
            alumnoid = request.form['alumnoid']
            return redirect(url_for("eliminarAlumnos", alumno_id = alumnoid))
        
    if request.method == "GET":
        if alumnoid:
            alumno_buscado = get_alumno_by_id(alumnoid)
            if alumno_buscado:
                return render_template("modificar_alumno.html", alumno = alumno_buscado)
            else:
                flash("DNI no registrado!!!", "danger")

    return render_template("modificar_alumno.html")

templates/consultar_alumno.html
{% extends 'layout.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <h1 style="color: white;">Consultando Alumnos...</h1>
        <div class="col-md-6 offser-md-3">
            {% with mensajes = get_flashed_messages(with_categories=true) %}
                    {% if mensajes %}
                        {% for categoria, mensaje in mensajes %}
                            <div class="alert alert-{{ categoria }}">
                                {{ mensaje }}
                            </div>
                        {% endfor %}
                    {% endif %}
            {% endwith %}
            <div class="card card-body mt-4">
                <!--Tu formulario aquí -->
                <form action="{{ url_for('alumnos.consulta') }}" method="POST">
                    <div class="form-group">
                        <label for="dni">DNI del Alumno a consultar</label>
                        <input type="text" id="dni" name="dni" placeholder="Ingrese el DNI" class="form-control">
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-success">Consultar Alumno</button>
                    </div>
                </form>
            </div>
            {% if alumno %}
                <div class="card card-body" style="margin-top: 20px;">
                    <h4>Datos del Alumno</h4>
                    <form>
                        <input type="hidden" id="alumnoid" name="alumnoid" value="{{ alumno['AlumnoID'] }}" readonly>
                        <div class="form-group">
                            <label for="dni">DNI</label>
                            <input type="text" id="dni" name="dni" value="{{alumno['AlumnoDNI']}}" class="form-control" readonly>
                        </div>
                        
                        <div class="form-group">
                            <label for="apellido">APELLIDO</label>
                            <input type="text" id="apellido" name="apellido" value="{{alumno['Apellido']}}" class="form-control" readonly>
                        </div>
                        
    
                        <div class="form-group">
                            <label for="nombre">NOMBRE</label>
                            <input type="text" id="nombre" name="nombre" value="{{alumno['Nombre']}}" class="form-control" readonly>
                        </div>
                        
                        <div class="form-group">
                            <label for="fecha">FECHA NACIMIENTO</label>
                            <input type="text" id="fecha" name="fecha" value="{{alumno['FechaNacimiento']}}" class="form-control" readonly>
                          </div>
    
                        <div class="form-group">
                            <label for="email">EMAIL</label>
                            <input type="text" id="email" name="email" value="{{alumno['Email']}}" class="form-control" readonly>
                          </div>
    
                        <div class="form-group">
                            <label for="telefono">TELEFONO</label>
                            <input type="text" id="telefono" name="telefono" value="{{alumno['Telefono']}}" class="form-control" readonly>
                        </div>
    
                    </form>

                </div>
            {% endif %}        
        </div>
    </div>
</div>
{% endblock %}

templates/eliminar_alumno.html
{% extends 'layout.html' %}
{% block body %}
    <h1>Eliminando Alumnos...</h1>

{% endblock %}

templates/index.html
{% extends 'layout.html' %}
{% block body %}
    <h1>Esta es la pagina principal</h1>

{% endblock %}

    

templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Page Title</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel="stylesheet" href="https://bootswatch.com/5/flatly/bootstrap.min.css">
    <link rel='stylesheet' href='static/css/styles.css'>
    <script src='main.js'></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav me-auto">
              <li class="nav-item">
                <a class="nav-link active" href="{{ url_for('index') }}">Inicio
                  <span class="visually-hidden">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('alumnos.registra') }}">Registrar</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('alumnos.consulta') }}">Consultar</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('alumnos.modifica') }}">Modificar/Eliminar</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('alumnos.lista') }}">Listar</a>
              </li>
              
            </ul>
            <form class="d-flex">
              <input class="form-control me-sm-2" type="search" placeholder="Search">
              <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
    {% block body %}


    {% endblock %}
</body>
</html>

templates/listar_alumno.html
{% extends 'layout.html' %}
{% block body %}
    

    <div class="container">
        <h1 style="color:white">Listando Alumnos...</h1>
        {% with mensajes = get_flashed_messages(with_categories=true) %}
                {% if mensajes %}
                    {% for categoria, mensaje in mensajes %}
                        <div class="alert alert-{{ categoria }}">
                            {{ mensaje }}
                        </div>
                    {% endfor %}
                {% endif %}
        {% endwith %}
        <table class="table table-striped table-bordered bg-white table-sm">
            <thead>
            <tr class="table-primary">
                <th scope="col">DNI</th>
                <th scope="col">Apellido</th>
                <th scope="col">Nombre</th>
                <th scope="col">Email</th>
                <th scope="col">Accion</th>
            </tr>
            </thead>
            <tbody>
                {% for user in total_alumnos %}
                <tr>
                    <th>{{user['AlumnoDNI']}}</th>
                    <td>{{user['Apellido']}}</td>
                    <td>{{user['Nombre']}}</td>
                    <td>{{user['Email']}}</td>
                    <td>
                        <a href="{{ url_for('alumnos.modifica', alumnoid=user['AlumnoID']) }}" class="btn btn-danger">Modificar</a>
                        <a href="{{ url_for('alumnos.eliminarAlumnos', id=user['AlumnoID']) }}" class="btn btn-danger">Eliminar</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
      </div>
{% endblock %}

templates/modificar_alumno.html
{% extends 'layout.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <h1 style="color: white;">Modificando Alumnos...</h1>
        <div class="col-md-6 offser-md-3">
            {% with mensajes = get_flashed_messages(with_categories=true) %}
                    {% if mensajes %}
                        {% for categoria, mensaje in mensajes %}
                            <div class="alert alert-{{ categoria }}">
                                {{ mensaje }}
                            </div>
                        {% endfor %}
                    {% endif %}
            {% endwith %}
            <div class="card card-body mt-4">
                <!--Tu formulario aquí -->
                <form action="{{ url_for('alumnos.modifica') }}" method="POST">
                    <div class="form-group">
                        <label for="dni">DNI del Alumno a modificar</label>
                        <input type="text" id="dni" name="dni" placeholder="Ingrese el DNI" class="form-control">
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-success" name="buscar" value="buscar">Consultar alumno</button>
                    </div>
                </form>
            </div>
            {% if alumno %}
                <div class="card card-body" style="margin-top: 20px;">
                    <h4>Datos del Alumno</h4>
                    <form action="{{ url_for('alumnos.modifica') }}" method="POST">
                        <input type="hidden" id="alumnoid" name="alumnoid" value="{{ alumno['AlumnoID'] }}" readonly>
                        <div class="form-group">
                            <label for="dni">DNI</label>
                            <input type="text" id="dni" name="dni" value="{{alumno['AlumnoDNI']}}" class="form-control" readonly>
                        </div>
                        
                        <div class="form-group">
                            <label for="apellido">APELLIDO</label>
                            <input type="text" id="apellido" name="apellido" value="{{alumno['Apellido']}}" class="form-control">
                        </div>
                        
    
                        <div class="form-group">
                            <label for="nombre">NOMBRE</label>
                            <input type="text" id="nombre" name="nombre" value="{{alumno['Nombre']}}" class="form-control">
                        </div>
                        
                        <div class="form-group">
                            <label for="fecha">FECHA NACIMIENTO</label>
                            <input type="text" id="fecha" name="fecha" value="{{alumno['FechaNacimiento']}}" class="form-control">
                          </div>
    
                        <div class="form-group">
                            <label for="email">EMAIL</label>
                            <input type="text" id="email" name="email" value="{{alumno['Email']}}" class="form-control">
                          </div>
    
                        <div class="form-group">
                            <label for="telefono">TELEFONO</label>
                            <input type="text" id="telefono" name="telefono" value="{{alumno['Telefono']}}" class="form-control">
                        </div>
                        <div class="form-group" style="margin-top: 6px;">
                            <button type="submit" class="btn btn-success" name="modificar" value="modificar">Modificar</button>
                            <button type="submit" class="btn btn-success" name="eliminar" value="eliminar">Eliminar</button>
                        </div>
    
                    </form>

                </div>
            {% endif %}        
        </div>
    </div>
</div>
{% endblock %}

templates/registrar_alumno.html
{% extends 'layout.html' %}
{% block body %}

<div class="container"> 

    <div class="row">
        <h1 style="color: white;">Registrando Alumnos...</h1>
        <div class="col-md-6 offser-md-3">
            {% with mensajes = get_flashed_messages(with_categories=true) %}
                    {% if mensajes %}
                        {% for categoria, mensaje in mensajes %}
                            <div class="alert alert-{{ categoria }}">
                                {{ mensaje }}
                            </div>
                        {% endfor %}
                    {% endif %}
            {% endwith %}
            <div class="card card-body mt-4">
                <!--Tu formulario aquí -->
                <form action="{{ url_for('alumnos.registra') }}" method="POST">
                    <div class="form-group">
                        <label for="dni">DNI</label>
                        <input type="text" id="dni" name="dni" placeholder="Dni" class="form-control">
                    </div>
                    
                    <div class="form-group">
                        <label for="apellido">APELLIDO</label>
                        <input type="text" id="apellido" name="apellido" placeholder="Apellido" class="form-control">
                    </div>
                    

                    <div class="form-group">
                        <label for="nombre">NOMBRE</label>
                        <input type="text" id="nombre" name="nombre" placeholder="Nombre" class="form-control">
                    </div>
                    
                    <div class="form-group">
                        <label for="fecha">FECHA NACIMIENTO</label>
                        <input type="text" id="fecha" name="fecha" placeholder="Fecha de Nacimiento" class="form-control">
                      </div>

                    <div class="form-group">
                        <label for="email">EMAIL</label>
                        <input type="text" id="email" name="email" placeholder="Email" class="form-control">
                      </div>

                    <div class="form-group">
                        <label for="telefono">TELEFONO</label>
                        <input type="text" id="telefono" name="telefono" placeholder="Telefono" class="form-control">
                    </div>


                    <div class="form-group">
                        <button type="submit" class="btn btn-success">Registrar</button>
                    </div>

                    
                </form>


            </div>




        </div>
    </div>
</div>
{% endblock %}